<?php
// Warning! NO EDIT THIS FILE!!!
// For Edit use Admin-Control-Panel Interface
// File Created:18:15:18 19.08.2008

define(actions, "Действия");
define(activate_im, "Активировать мой IM (MSN, Gtalk и т.д..)");
define(added_as_friend_mail, "Здравствуйте, #recipient_name!\n#username (http://ReVou.com/profile/#username)\nдобавил Вас в свой список друзей.\n\nС уважением,\nКоманда ReVou");
define(added_as_friend_sms, "Здравствуйте, #recipient_name! #username добавил Вас в свой список друзей на ReVou");
define(added_as_friend_subject, "#username добавил Вас в список друзей");
define(add_me, "Добавить меня");
define(all_friends, "Показать всех моих друзей");
define(api_key_explanation, "Ключ API необходим для приложений, использующих ReVou API. Вы должны использовать его каждый раз при вызове API методов.");
define(api_key_header, "Ключ к моему API");
define(api_key_is, "Ваш API ключ:");
define(a_add, "Добавить");
define(a_as_friend, "как друга");
define(a_block, "Заблокировать");
define(a_follow, "Подписаться");
define(a_leave, "Отменить подписку");
define(a_nudge, "Напомнить");
define(a_remove, "Удалить");
define(a_send_msg, "Отправить сообщение ");
define(big_or, "ИЛИ");
define(block_ok, "#username заблокирован");
define(bm_about, "О нас");
define(bm_api, "API");
define(bm_contact, "Связаться с нами");
define(bm_help, "Помощь");
define(bm_privacy, "Политика безопасности");
define(bm_terms, "Правила использования");
define(buy, "КУПИТЬ");
define(buying_instruction, "Чтобы купить еще, выберите, сколько дополнительных SMS вы хотите приобрести, и нажмите кнопку КУПИТЬ.");
define(buy_failure, "К сожалению, произошла ошибка во время транзакции.");
define(buy_failure_title, "Новые SMS единицы добавлены.");
define(buy_success1, "Транзакция прошла успешно,");
define(buy_success2, "sms единицы добавлены в ваш аккаунт");
define(buy_success_error, "Данная транзакция уже завершена или не существует. Пожалуйста, повторите попытку.");
define(buy_success_error_title, "Ошибка транзакции");
define(buy_success_title, "Новые SMS единицы добавлены");
define(chars_left, "осталось символов");
define(check_all, "Выбрать все");
define(choose_bglib, "Выбрать из библиотеки фонов:");
define(choose_sms_plan, "Выберите SMS план");
define(choose_your_photo, "Выбрать фото из библиотеки");
define(comma_separated_200chr, "Через запятую, max 200 символов");
define(confirmation_mail, "Здравствуйте, #username!\nВы только что присоединились к ReVou. Перейдите по ссылке ниже и завершите регистрацию:\n#link\n\nЧтобы активировать MSN или Gtal");
define(confirmation_subject, "Добро пожаловать в ReVou!");
define(contact_us, "Связаться с нами");
define(credits_for, "выдать за");
define(credit_amount, "Сумма на счете");
define(credit_price, "1 SMS единица стоит");
define(days_ago, "дней назад");
define(default_message_from_admin, "Добро пожаловать в ReVou! Мы надеемся, Вам понравится сайт. Если у Вас есть вопросы, посетите секцию HELP или задайте их на по электронной почте в");
define(direct_msg, "Личное сообщение");
define(direct_msgs_to, "Личное сообщение");
define(direct_notification_mail, "Здравствуйте, #recipient_name!\n#author_name (#author_link) \nотправил Вам сообщение:\n\n#message\n\nС уважением,\nКоманда ReVou");
define(direct_notification_sms, "Здравствуйте,  #recipient_name! #author_name отправил Вам сообщение на ReVou");
define(direct_notification_subject, "#username отправил Вам сообщение!");
define(enter_some_emails, "Заполните email адреса Ваших друзей и мы отправим им приглашения.");
define(err_about_me_too_long, "Длина текста в разделе «О себе» не может превышать 200 символов.");
define(err_accept_terms, "Согласитесь с Правилами использования");
define(err_account_exists, "Аккаунт с таки именем уже существует.");
define(err_account_inactive, "Аккаунт не активен. Активируйте свой аккаунт, чтобы войти в систему. Для этого используйте ссылку, высланную на Ваш email. Если Вы не получили ");
define(err_choose_name, "Выберите имя пользователя.");
define(err_create_account, "Аккаунт не создан. Повторите попытку позже.");
define(err_email, "Произошла ошибка при отправке сообщения. Пожалуйста, попробуйте еще раз.");
define(err_email_confirmation_needed, "Активируйте свой аккаунт, чтобы войти в систему. Для этого используйте ссылку, высланную на Ваш email. Если Вы не получили сообщение, проверьт");
define(err_email_exists, "Аккаунт с таким email адресом уже существует. Выберите другой.");
define(err_email_incorrect, "Введен неправильный email адрес.");
define(err_email_needed, "Пожалуйста, укажите свой email.");
define(err_email_not_found, "Данный email адрес не существует в нашей базе данных.");
define(err_file_too_large, "Размер файла не может превышать 500 Kb");
define(err_fill_all, "Пожалуйста, заполните все поля формы.");
define(err_interests_too_long, "Длина текста в разделе «Интересы» не может превышать 200 символов.");
define(err_invalid_code, "Введен неправильный код.");
define(err_invitations, "Произошла ошибка при отправке приглашения.");
define(err_layout_change, "Произошла ошибка при изменении внешнего вида аккаунта.");
define(err_life_change, "Произошла ошибка во время изменения информации о Вас.");
define(err_login_incorrect, "Неправильный логин.");
define(err_mobile, "Произошла ошибка во время сохранения номера Вашего мобильного телефона.");
define(err_msg_too_long, "Сообщение слишком длинное. Длина сообщения не может превышать 140 символов.");
define(err_password_mismatch, "Пароль и его подтверждение не совпадают.");
define(err_photo_upload, "Ваше фото не загружено. Убедитесь, что выбрали правильный формат файла.");
define(err_reminder_error, "Произошла ошибка при восстановлении пароля.");
define(err_set_im, "Ваш IM не активирован");
define(err_sms_limit, "Задайте ограничение на количество SMS.");
define(err_sms_limit_nan, "Количество SMS должно быть целым числом.");
define(favorites_header, "Избранное");
define(followers_of1, "Подписчик");
define(followers_of2, "");
define(follow_4_steps, "Выполните 4 простых шага, чтобы создать свой аккаунт:");
define(follow_ok, "Вы следуете за #username сейчас");
define(forgot_header, "Забыли пароль?");
define(forgot_paragraph, "Если Вы забыли свой пароль, введите свой email адрес, и пароль сразу же будет выслан.");
define(friends1, "Друзей ");
define(friends2, "");
define(friends_of1, "Друзей");
define(friends_of2, "");
define(friend_search, "Искать друзей");
define(from, "от");
define(gateway_info, "Номер нашей SMS службы: ");
define(hello, "Здравствуйте");
define(hours_ago, "часов назад");
define(hour_ago, "час назад");
define(import_contacts_from, "Импортировать свои данные с");
define(im_msg_too_long, "Ваше сообщение слишком длинное и было сокращено до 140 символов: ");
define(inbox, "Входящие");
define(invitation_mail, "Здравствуйте!\nНаш сайт — это сервис, который спрашивает \"Что ты сейчас делаешь?\".\nМое последнее сообщение:\n\n#last_update\n#message_link\n\nА ты что сейча");
define(invitation_preview1, "Здравствуйте,!\nReVou это сайт, который спрашивает \"Что ты сейчас делаешь?\".\nМое последнее сообщение:");
define(invitation_preview2, "А ты что сейчас делаешь? Зарегистрируйтесь на ReVou и скажи другому!\n\nС уважением,");
define(invitation_subject, "Приглашение на ReVou");
define(invite_header, "Пригласи своих друзей!");
define(invite_paragraph, "Заполни свои данные и найди своих друзей на ReVou");
define(in_reply_to, "@");
define(i_accept, "Я принимаю");
define(i_accept2, "");
define(i_am_in, "Место жительства");
define(label_about_me, "О себе:");
define(label_back_color, "Цвет фона:");
define(label_back_default, "Вернуть настройки по умолчанию");
define(label_back_fixed, "Фиксированный фон:");
define(label_back_image, "Изображение фона:");
define(label_border_color, "Цвет границы:");
define(label_bubble_fill, "Цвет вашего обновленного фона:");
define(label_bubble_text, "Цвет вашего обновленного текста:");
define(label_captcha2, "Код:");
define(label_catcha1, "Код безопасности:");
define(label_catcha2, "Подтвердите код:");
define(label_check_now, "Проверить сейчас");
define(label_choose_this_photo, "Выбрать это фото");
define(label_create_account, "Создать аккаунт");
define(label_deactivate, "Отключить мой IM");
define(label_delete, "Удалить");
define(label_delete_account, "Удалить мой ReVou аккаунт сейчас!");
define(label_dob, "Дата рождения:");
define(label_email, "e-mail:");
define(label_emails, "Email адреса:");
define(label_flag_send_message, "");
define(label_follow, "Подписаться");
define(label_full_name, "Полное имя:");
define(label_groups, "label_groups");
define(label_im_id, "E-mail или Ваш IM ID:");
define(label_im_type, "Instant Messenger:");
define(label_interests, "Интересы:");
define(label_invite, "Пригласить");
define(label_lang, "Language");
define(label_link_color, "Цвет ссылки:");
define(label_location, "Место жительства:");
define(label_login, "Логин");
define(label_message, "Сообщение:");
define(label_more_info, "Подробнее URL:");
define(label_msg_area, "Цвет фона сообщения:");
define(label_password, "Пароль:");
define(label_remember, "Запомнить меня");
define(label_remind, "Напомнить сейчас");
define(label_remove_account, "Удалить мой аккаунт");
define(label_repeat_pass, "Повторите пароль:");
define(label_reply, "ответить");
define(label_save_changes, "Сохранить изменения");
define(label_search, "Начать!");
define(label_send, "Отправить");
define(label_side_fill, "Цвет фона бокового блока:");
define(label_sticker_color, "Цвет информера:");
define(label_stop_following, "Отменить подписку");
define(label_subject, "Тема:");
define(label_text_color, "Цвет текста:");
define(label_tile_image, "Мозаика:");
define(label_uname_email, "Имя вашего пользователя или email:");
define(label_upload_now, "Закачать сейчас");
define(label_url, "У вас есть блог? Введите ссылку здесь");
define(label_user_name, "Имя пользователя:");
define(label_use_image, "Использовать изображение");
define(label_your_email, "Ваш email:");
define(label_your_name, "Ваше имя:");
define(label_your_uname, "Ваше имя (без пробелов между буквами и словами:");
define(leave_ok, "Вы покинули #username");
define(life_header, "О себе");
define(limit_200chr, "Максимальная длина: 200 символов");
define(link_continue, "Продолжить");
define(link_finish, "ЗАКОНЧИТЬ");
define(link_login, "Логин");
define(link_register, "Зарегистрироваться");
define(link_start, "Начать!");
define(main_header, "Скажи миру, что ты делаешь сейчас!");
define(max500, "Максимальный размер картинки 500 kb.");
define(member_of, "Член ReVou");
define(menu_home, "Главная");
define(menu_invite, "Пригласить друзей");
define(menu_logout, "Выход");
define(menu_my_panel, "Моя панель");
define(menu_settings, "Настройки");
define(menu_vision, "Vision Map");
define(mins_and, "минут и");
define(minutes_ago, "минут назад");
define(min_and, "минуту и");
define(my_account, "Мой аккаунт");
define(my_groups_header, "");
define(my_im_explanation, "Активация вашего IM позволит отправлять и принимать сообщения других пользователей.");
define(my_im_header, "Мой Instant Messenger");
define(my_lay_background, "Фон");
define(my_lay_boxes, "Блоки справа");
define(my_lay_bubble, "Фон сообщения");
define(my_lay_header, "Внешний вид моего аккаунта");
define(my_lay_other, "Другое");
define(my_mobile, "Мой мобильный");
define(my_mobile_header, "Номер моего мобильного");
define(my_mobile_label, "Номер Вашего мобильного:");
define(my_mobile_text, "Укажите номер Вашего мобильного телефона (включая код старны +хх), чтобы отправлять и получать сообщения и напоминания от ReVou! Будьте всегда");
define(my_profile_header, "Мой профиль");
define(my_sms_credits, "Счет моих SMS");
define(name_and_mail, "Имя и email");
define(new_msg_notify, "Сообщать мне о новых сообщениях:");
define(no, "НЕТ");
define(notification_comment, "Сообщать мне, когда кто-то подписывается на мой аккаунт");
define(notification_header, "Email уведомление");
define(notification_label, "Сообщать мне о новых подписчиках:");
define(notification_mail, "Здравствуйте, #recipient_name!\n#author_name (#author_link) \nдобавил сообщение на ReVou.com:\n\n#message\n\nС уважением,\nКоманда ReVou");
define(notification_sms, "Здравствуйте, #recipient_name! #author_name добавил сообщение: #message");
define(notification_subject, "Новое сообщение на ReVou.com от #username!");
define(notify_any_type, " любого типа от пользователей, на которых я подписывался (лась)");
define(notify_by, "Сообщать мне:");
define(notify_direct_only, " только о личных сообщениях пользователей, на которых я подписывался (лась)");
define(notify_way_err, "Произошла ошибка во время изменения режима уведомления на ");
define(notify_way_ok, "OK, режим уведомления изменен на ");
define(no_contacts_found, "Не найдено ни одного контакта");
define(no_msg, "Нет сообщений");
define(nudge, "Привет! Почему ты ничего не пишешь на ReVou.com? Я не могу ждать!");
define(nudge_ok, "#username получил напоминание");
define(nudge_subject, "Напоминание от ReVou.com");
define(n_email, "e-mail");
define(n_im, "IM");
define(n_sms, "SMS");
define(n_web, "только на сайте");
define(ok_added_as_friend, "Данный пользователь добавлен в Список Ваших друзей.");
define(ok_back_to_defaults, "Ваши настройки восстановлены по умолчанию.");
define(ok_email_sent, "Ваше сообщение отправлено. Спасибо.");
define(ok_im_deactivated, "Ваш IM отключен.");
define(ok_im_set, "Ваш IM активирован. Теперь Вы можете добавить <span id='im_contact'>#contact</span> в Ваш контакт лист");
define(ok_invitations_sent, "Приглашения отправлены всем или выбранным контактам, зарегистрированным в системе и добавленным в Ваш Список друзей.");
define(ok_invitations_sent_nolist, "Приглашения отправлены всем или выбранным контактам, а также зарегистрированным пользователям, добавленным в Ваш Список друзей.");
define(ok_layout_changed, "Внешний вид Вашего аккаунта изменен.");
define(ok_life_changed, "Информация о Вас изменена.");
define(ok_life_saved, "Информация о Вас сохранена.");
define(ok_msg_sent, "Ваше сообщение отправлено.");
define(ok_phone_saved, "Номер Вашего мобильного телефона сохренен. Теперь Вы можете отправлять сообщения при помощи SMS на этот номер: ");
define(ok_photo_changed, "Ваше фото изменено.");
define(ok_photo_uploaded, "Ваше фото загружено.");
define(ok_profile_saved, "Ваш профайл сохранен.");
define(ok_reminder_sent, "Новый пароль выслан на Ваш email.");
define(ok_reply_sent, "Ваш ответ отправлен.");
define(ok_settings_saved, "Ваши настройки сохранены.");
define(ok_sms_limit_set, "Ограничение количества SMS установлено.");
define(option_day, "День");
define(option_month, "Месяц");
define(option_year, "Год");
define(outbox, "Исходящие");
define(pagination_next, "Следующая");
define(pagination_page, "Страница");
define(pagination_prev, "Предыдущая");
define(pass_not_stored, "Ваши имя пользователя и пароль не будут храниться на нашем сервере.");
define(paste_code_flash, "Вставьте этот код в вашу веб страницу/блог:");
define(people_interested_in, "Люди, заинтересованные в");
define(photo_header, "Locationое фото");
define(profile_del_explanation, "Если Вы хотите удалить ваш ReVou профайл, нажмите на кнопку ниже. После этого Ваш аккаунт не может быть восстановлен, поэтому подумайте дважды");
define(profile_del_header, "Удалить мой аккаунт");
define(profile_del_u_sure, "Вы уверены, что хотите удалить Ваш ReVou аккаунт?");
define(profile_tab_customize, "Кастомизировать ReVou");
define(profile_tab_mine, "Мои сообщения");
define(profile_tab_replys, "Публичные ответы");
define(profile_tab_with_friends, "Сообщения ваших друзей");
define(qty_direct_msg, "личных сообщений");
define(qty_favorites, "избранных");
define(qty_followers, "подписчиков");
define(qty_friends, "друзей");
define(qty_sms_credits, "оставшихся sms");
define(qty_updates, "сообщений");
define(refresh_warning, "Если картинка не изменилась, обновите страницу, используя Ctrl+F5");
define(reminder_mail, "Здравствуйте, #user!\nВаш пароль на ReVou: #pass\n\nС уважением, \nКоманда ReVou");
define(reminder_subject, "Восстановление пароля от ReVou");
define(remove_ok, "#username был удален");
define(reply_to_msg, "Ответить на сообщение:");
define(reset_sms_limit, "Переустановить");
define(results_for, "Результаты для");
define(save, "Save");
define(secs_ago, "секунд назад");
define(send_msg_to, "Отправить сообщение");
define(separate_commas, "отделенные запятой");
define(settings, "Настройки");
define(setting_err, "Произошла ошибка во время изменения ваших настроек.");
define(setting_ok, "OK, настройки изменены");
define(set_limit_button, "Установить сейчас");
define(set_limit_to, "Установить ваш SMS лимит в");
define(set_sms_limit, "Установить SMS лимит");
define(skip_setup, "Пропустить установку");
define(sms_credits_title, "Счет ваших смс");
define(sms_limit_header, "SMS лимит");
define(sms_limit_text, "Чтобы сэкономить на дополнительных SMS, вы можете установить лимит отправленных/полученных SMS. Лимит может быть изменен в любое время.");
define(step1, "Шаг 1: Добавьте ваше фото");
define(step2, "Шаг 2: Активируйте ваш Instant Messenger");
define(step3, "Шаг 3: Заполните подробная информацию о себе");
define(step4, "Шаг 4: Пригласите своих друзей");
define(sticker_choose_color, "Выберите цвет вашего информера:");
define(sticker_flash, "Flash информер");
define(sticker_friends_comment, "Нижеприведенный код создаст HTML информер, отображающий список пользователей, на которых вы подписались:");
define(sticker_header, "Мои информеры");
define(sticker_js, "JavaScript информер");
define(sticker_js_comment, "Вам нужно что-то более простое для возможности кастомизации с использованием CSS? Вставьте этот код в вашу веб страницу/блог:");
define(tab_picture_set, "Библиотека картинок");
define(tab_popular, "Самое популярное");
define(tab_recent, "Недавнее");
define(tab_upload, "Закачать");
define(text_on_black, "");
define(tile_both, "Мозаика вертикально и горизонтально");
define(tile_h, " Мозаика горизонтально");
define(tile_no, "Отменить мозаику");
define(tile_v, "Мозаика вертикально");
define(title_delete, "Удалить это сообщение");
define(title_fav_add, "Добавить в избранное");
define(title_fav_del, "Удалить из избранного");
define(title_reply, "Ответить на это сообщение");
define(to, "кому");
define(total_price, "общая сумма составить");
define(trans_credits, "Купленных единиц");
define(trans_date, "Дата транзакции");
define(trans_time, "Время транзакции");
define(trans_value, "Стоимость");
define(twitter_com_account_header, " Âàø àêêàóíò íà Twitter.com ");
define(twitter_com_account_password, "");
define(twitter_com_account_username, "");
define(unblock, "разблокировать");
define(unblock_ok, "#username разблокирован");
define(uncheck_all, "Отменить выделение");
define(updates_protected, "Только мои друзья могут видеть мои обновления.");
define(upload_comment, "Покажи другим свою улыбку!");
define(upload_hint, "Максимальный размер файла 1 Мб, допустимые форматы: jpeg/png/gif");
define(upload_picture, "Добавить картинку (jpeg/gif/png):");
define(upload_your_photo, "Закачать ваше фото");
define(used_credits_below_limit, "Использованных единиц");
define(users_message, "Сообщение ");
define(users_profile, " профиль");
define(user_first_message, "Добавлены к ReVou :)");
define(u_about, "О себе");
define(u_age, "Возраст:");
define(u_bio, "Обо мне:");
define(u_fullname, "Имя:");
define(u_interests, "Интересы:");
define(u_location, "Место жительства:");
define(u_www, "WWW:");
define(visibility, "Сделать мои сообщения видимыми всем пользователям, а не только моим друзьям");
define(welcome, "Добро пожаловать в ReVou");
define(welcome_info1, "Ваш аккаунт на ReVou был создан, но необходимо его активировать. Чтобы это сделать, перейдите по ссылке, отправленной на ваш email.");
define(welcome_info2, "Не забудьте проверить сообщение в папке СПАМ.");
define(we_found1, "Мы нашли");
define(we_found2, "из Ваших контактов");
define(what_are_you_doing, "Что ты делаешь?");
define(yes, "ДА");
define(yesterday, "вчера");
define(your_limit_is, "Ваш лимит составляет");
define(your_reply, "Ваш ответ:");
define(your_sms_transactions, "SMS планы, которые вы приобрели");
define(you_have, "Сейчас у вас");

?>