{if $logged_user}
	<h1>Terms and Conditions</h1>
{else}
	<h1 class='header'>Terms and Conditions</h1>
{/if}
<h2>
August 3, 2007</h2>
<p>This agreement establishes the terms obrigacionais that will govern the legal relationship between the site and its users twittr.com.</p>
<p>twittr.com gives you a limited license to access the site and use its services in accordance with these Terms and instructions found on the site. twittr.com it reserves the right to terminate its license to use the site and its services at any time and for any reason or in the future charge for their use commercially.</p>
<h2>Responsibilities of the User</h2>
<p>To use the site you should be greater than 14 years of idade.Você are solely responsible for your use of the site and its services. Even if the twittr.com only function as a repository of information, the content generated by the user does not represent the views and opinions of twittr.com. twittr.com enables the link to third party sites, but its content and its policies are not under our control and we are not responsible for any content of these sites. The inclusion of a link on our site and their services does not represent any endorsement or affiliation by the twittr.com. You agree that the only solution is you stop using the site.</p>
<h2>Content generated by the user</h2>
<p>When publishing any contents, you are giving to us and other users access and use of it. twittr.com is not responsible for the event or the circumstances in which third parties to access or use the public and has no obligation to restrict such access. twittr.com has the power to recover and remove its contents and personal information of the site and its services.</p>
<p>The content below are expressly forbidden to be published by its users:</p>
<ul>
<li>Content involving nudity - is explicit photos of women "topless" or parts obscenas.</li>
<li>Material and Marks with copyrights that were used without permission expressed by the author </li>
<li>Pornography and obscene content</li>
<li>Content that exploits children and minors of age</li>
<li>Content that believe they have been published with malicious purposes, including defamation, libel or persecution </li>
<li>Content that can be judged offensive to the community of twittr.com including, but not limited to expressions descaradas of fanaticism, racism, prejudice, hatred and sacrilegious</li>
<li>Content that promotes or submit instructional information about illegal activities</li>
<li>Content that transmit or contain viruses, corrupted files or similar elements </li>
</ul>
<p>The twittr.com examines the content posted by users periodically and if gives the absolute right (but not the obligation) to remove any content that is not in the standards listed above.</p>
<h2>Forum of Election</h2>
<p>Any dispute concerning this Agreement or the site will be resolved in court in line with the Brazilian law, leaving the main forum in the city of Sao Paulo elected as the only competent to deal this issue.</p>
<h2>Final Provisions</h2>
<p>This Agreement shall be governed by the laws of Brazil and meet the Brazilian legal system, the general principles of law and international standards for e-commerce.</p>
<p>If the user does not agree with certain provision of this Agreement, and get legal invalidity of the same, other devices will not be harmed and will remain in force.</p>
<p>If the user has any doubt on this agreement or on the practices of this site, please contact us.</p>
<p>EU LI AND COMPREENDI THE TERMS AND PROVISIONS OF THIS AGREEMENT FOR USE AND I'M AWARE OF YOUR ENTIRE CONTENTS, BY ACCEPTING THEIR CONDITIONS.</p>