<?php
define("db_host","localhost");
define("db_name","teletele");
define("db_user","teletele");
define("db_pass","QAs9fStScUXb4Ca2");
define("db_type","MySQL");
define("MAX_LOGIN_ATTEMPTS","3");
define("MAX_FRIENDS","2");
define("PIN_MIN","10000");
define("PIN_MAX","99999");
define("SMS_MIN","1");
define("SMS_MAX","2");
define("AGE_MIN","1");
define("AGE_MAX","150");
define("MAX_TRIALS","6");
define("FIRST_EXTENSION","1000");
define("LAST_EXTENSION","9999");
define("SYSTEM_ADMIN","apierce@noetic.org");
define("TWILIO_USER","adelorme@noetic.org");
define("TWILIO_PASS","123456ad");
define("TWILIO_PHONE","877-877-7530");
//define("TWILIO_USER","gre.bris@gmail.com");
//define("TWILIO_PASS","B4ts.birds");
//define("TWILIO_PHONE","(315)605-2265");
define("MODE_READONLY","readonly");
?>